### ISSUE TITLE
Export of preferences not working (Export All)

### ISSUE THREAD

**Issue by ansu1141** [mkesting/jautodoc#8]
Hi,
I'm using Eclipse 2022-03 with Java 17.0.2. Every time I try to export the preferences I get the following exception:

`java.lang.NoClassDefFoundError: Could not initialize class com.sun.xml.bind.v2.runtime.reflect.opt.Injector
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:41)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:77)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:317)
	at com.sun.xml.bind.v2.runtime.property.SingleElementNodeProperty.<init>(SingleElementNodeProperty.java:52)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
...
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:372)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:574)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:522)
	at net.sf.jautodoc.utils.JAXBSerializer.doExport(JAXBSerializer.java:43)
	at net.sf.jautodoc.preferences.PreferenceSerializer.doExport(PreferenceSerializer.java:40)
	at net.sf.jautodoc.preferences.MainPreferencePage.performExport(MainPreferencePage.java:478)
	at net.sf.jautodoc.preferences.MainPreferencePage.access$2(MainPreferencePage.java:467)
	at net.sf.jautodoc.preferences.MainPreferencePage$3.widgetSelected(MainPreferencePage.java:187)
...

**Comment by mkesting** [comment]
It’s because Java 17 denies all illegal access operations by default. Adding the following line to the end of eclipse.ini should solve the problem:

`--add-opens=java.base/java.lang=ALL-UNNAMED`
